# ---------------------------------------------------------------------------- #
#                          DEVELOPMENT DOCKER COMPOSE                          #
# ---------------------------------------------------------------------------- #
services:

  db:
    image: postgres:17.5
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db-webui:
    image: clidey/whodb
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - WHODB_POSTGRES_1={"host":"db","user":"root","password":"root","database":"postgres"}

volumes:
  pgdata:
