# ---------------------------------------------------------------------------- #
#                          DEVELOPMENT DOCKER COMPOSE                          #
# ---------------------------------------------------------------------------- #
services:

  downtime-panda:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80

  db:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  db-webui:
    image: clidey/whodb
    restart: always
    ports:
      - 8081:8080
    environment:
      - WHODB_POSTGRES_1={"host":"db","user":"root","password":"root","database":"postgres"}
