# ---------------------------------------------------------------------------- #
#                          DEVELOPMENT DOCKER COMPOSE                          #
# ---------------------------------------------------------------------------- #
services:

  downtime-panda:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully

  db:
    image: postgres:17.5
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "root"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  flyway:
    image: flyway/flyway
    restart: no
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/postgres?connectTimeout=30&currentSchema=public&charSet=UTF-8
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=root
    volumes:
      - ./database/migrations:/flyway/sql
    command: migrate
    depends_on:
      db:
        condition: service_healthy

  db-webui:
    image: clidey/whodb
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - WHODB_POSTGRES_1={"host":"db","user":"root","password":"root","database":"postgres"}
