site_name: downtime-panda

repo_url: https://github.com/Mikel12455/downtime-panda/
repo_name: Downtime Panda

theme:
  name: "material"

markdown_extensions:
  - admonition

plugins:
- search
- mkdocs-autoapi:
    autoapi_dir: src
- mkdocstrings:
    handlers:
      python:
        paths: [src]

nav:
  - Indice: index.md
  - Architettura: architecture.md
  - Guida allo sviluppo: developer-guide.md
