site_name: downtime-panda

repo_url: https://github.com/Mikel12455/downtime-panda/
repo_name: Downtime Panda

theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: src
      autoapi_add_nav_entry: Reference
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - caption

nav:
  - Indice: index.md
  - Guida allo sviluppo: 1-developer-guide.md
  - Architettura: 2-architecture.md
  - Caratteristiche: 3-features.md
  - Sviluppi Futuri: 4-future-developments.md
