site_name: downtime-panda

repo_url: https://github.com/Mikel12455/downtime-panda/
repo_name: Downtime Panda

theme:
  name: "material"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: src
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Indice: 1-index.md
  - Guida allo sviluppo: 2-developer-guide.md
  - Architettura: 3-architecture.md
  - Caratteristiche: 4-features.md
  - Sviluppi Futuri: 5-future-developments.md
