# https://taskfile.dev

version: "3"

tasks:
  docker-build:
    cmds:
      - docker build -t downtime-panda .

  dev-up:
    cmds:
      - docker compose -f docker-compose.dev.yml up -d --build
      - task: run-flask

  dev-down:
    cmds:
      - docker compose -f docker-compose.dev.yml down --remove-orphans

  dev-migrate:
    vars:
      BIND_MOUNT: "--mount type=bind,src=${PWD}/database/migrations,dst=/flyway/sql"
      DB_URL: "jdbc:postgresql://db:5432/postgres?connectTimeout=30&currentSchema=downtime_panda&charSet=UTF-8"
    cmds:
      - docker run --net="downtime-panda_default" --rm {{.BIND_MOUNT}} -e "FLYWAY_URL={{.DB_URL}}" -e "FLYWAY_USER=root" -e "FLYWAY_PASSWORD=root" flyway/flyway migrate

  dev-migrate-clean:
    vars:
      BIND_MOUNT: "--mount type=bind,src=${PWD}/database/migrations,dst=/flyway/sql"
      DB_URL: "jdbc:postgresql://db:5432/postgres?connectTimeout=30&currentSchema=downtime_panda&charSet=UTF-8"
    cmds:
      - docker run --net="downtime-panda_default" --rm {{.BIND_MOUNT}} -e "FLYWAY_CLEAN_DISABLED=false" -e "FLYWAY_URL={{.DB_URL}}" -e "FLYWAY_USER=root" -e "FLYWAY_PASSWORD=root" flyway/flyway clean
      - task: dev-migrate

  make-migration:*:
    vars:
      DESCRIPTION: "{{index .MATCH 0}}"
      TODAY: "{{now}}"
      FOLDER: "./database/migrations"
    cmds:
      - echo -- Migration {{.TODAY | date "2006/01/02 15:04:05"}} > {{.FOLDER}}/V{{.TODAY | date "20060102150405"}}__{{.DESCRIPTION | lower}}.sql

  run-flask:
    vars:
      PORT: 8080
      HOST: 127.0.0.1
    env:
      DTPANDA_DB_DIALECT: postgresql+psycopg
      DTPANDA_DB_HOST: localhost
      DTPANDA_DB_PORT: 5432
      DTPANDA_DB_USER: root
      DTPANDA_DB_PASSWORD: root
      DTPANDA_DB_DATABASE: postgres
    cmds:
      - uv run flask --app downtime_panda run --port {{.PORT}} --host {{.HOST}} --debug
