# https://taskfile.dev

version: "3"

tasks:
  dev-up:
    cmds:
      - docker compose -f docker-compose.dev.yml up -d --build
      - uv run flask --app downtime_panda:app run --port 8080 --host 127.0.0.1 --debug

  dev-down:
    cmds:
      - docker compose -f docker-compose.dev.yml down --remove-orphans

  dev-migrate:
    vars:
      BIND_MOUNT: "--mount type=bind,src=${PWD}/database/migrations,dst=/flyway/sql"
      DB_URL: "jdbc:postgresql://db:5432/postgres?connectTimeout=30&currentSchema=public&charSet=UTF-8"
    cmds:
      - docker run --net="downtime-panda_default" --rm {{.BIND_MOUNT}} -e "FLYWAY_URL={{.DB_URL}}" -e "FLYWAY_USER=root" -e "FLYWAY_PASSWORD=root" flyway/flyway migrate

  make-migration:*:
    vars:
      DESCRIPTION: "{{index .MATCH 0}}"
      TODAY: "{{now}}"
      FOLDER: "./database/migrations"
    cmds:
      - echo -- Migration {{.TODAY | date "2006/01/02 15:04:05"}} > {{.FOLDER}}/V{{.TODAY | date "20060102150405"}}__{{.DESCRIPTION | lower}}.sql

  run-flask:
    cmds:
      - uv run flask --debug --app downtime_panda:app run
