# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  run-flask:
    cmds:
      - uv run flask --debug --app downtime_panda:app run
