"""move_name_to_subscription

Revision ID: 205be8f58c10
Revises: 339378a5d318
Create Date: 2025-06-20 11:05:26.329948

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "205be8f58c10"
down_revision = "339378a5d318"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.drop_column("name")

    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name", sa.String(length=255), nullable=False, server_default="test"
            )
        )
        batch_op.alter_column("name", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.drop_column("name")

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name", sa.VARCHAR(length=255), nullable=False, server_default="test"
            )
        )
        batch_op.alter_column("name", server_default=None)

    # ### end Alembic commands ###
