"""ping_response_time

Revision ID: 2fb8c8d409d7
Revises: 205be8f58c10
Create Date: 2025-06-20 11:56:27.476034

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fb8c8d409d7"
down_revision = "205be8f58c10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ping", schema=None) as batch_op:
        batch_op.add_column(sa.Column("response_time", sa.Interval(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ping", schema=None) as batch_op:
        batch_op.drop_column("response_time")

    # ### end Alembic commands ###
