"""bigint_to_int_for_sqlite

Revision ID: 339378a5d318
Revises: 3c5d5af9ad2f
Create Date: 2025-06-20 11:03:30.233184

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "339378a5d318"
down_revision = "3c5d5af9ad2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_token", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ping", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "service_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
        )

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "service_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.alter_column(
            "service_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ping", schema=None) as batch_op:
        batch_op.alter_column(
            "service_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("api_token", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    # ### end Alembic commands ###
