"""uuid_on_subscription_table

Revision ID: 47f6d32c11b2
Revises: e76f94629bb5
Create Date: 2025-06-02 13:52:00.343488

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47f6d32c11b2"
down_revision = "e76f94629bb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.Uuid(), nullable=False))
        batch_op.alter_column("user_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.alter_column("service_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.create_primary_key(
            batch_op.f("pk_subscription"), ["user_id", "service_id"]
        )
        batch_op.create_index(batch_op.f("ix_subscription_uuid"), ["uuid"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_uuid"))
        batch_op.drop_constraint(batch_op.f("pk_subscription"), type_="primary")
        batch_op.alter_column("service_id", existing_type=sa.BIGINT(), nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.BIGINT(), nullable=True)
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
